# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # Build in Go base container
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/Ankr-network/ankr-cli
    steps:
      - checkout
      - setup_remote_docker
      - add_ssh_keys:
          fingerprints:
            - "91:de:2e:da:16:ab:18:de:71:0f:e2:bf:5f:44:5c:55"
      - run:
          name: Copy ssh key in the circleci build context
          command: |
            cp ${HOME}/.ssh/id_rsa id_rsa
      - run:
          name: Install AWSCLI
          command: |
            curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
            unzip awscli-bundle.zip
            sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
      - run:
          name: Login to AWS ECR
          command: eval $(aws ecr get-login --no-include-email --region $AWS_REGION)
      - run:
          name: "Test, Build & Push Docker Image"
          command: |
            BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
            SHA1_SHORT=$(git rev-parse --short HEAD)
            DATE=`date +%Y%m%d%H%M%S`
            URL_BRANCH=""
            if [[ ($BRANCH_NAME == "master") ]]
            then
              BRANCH_NAME="stage"
            elif [[ ($BRANCH_NAME == "develop") ]]
            then
              BRANCH_NAME="dev"
            else
              BRANCH_NAME="feat"
            fi
            export URL_BRANCH

            docker build --label=ankr-cli -t ankr-cli:$BRANCH_NAME .